### ISSUE TITLE
ERROR DURING INSTALLATION

### ISSUE THREAD

**Issue by cmtcl18** [romerogroup/DMFTwDFT#5]
Dear Developers,
I tried to install  `DMFTwDFT` as the interface with `VASP`.  I downloaded  `DMFTwDFT`  from `https://github.com/DMFTwDFT-project/DMFTwDFT.git`. The `src_post-tools`  does not have `skrams`.
 
while compiling `DMFT.py -dft vasp -relax -dmft `, I am getting the following error. 

> Traceback (most recent call last):
  File "/home/jatin/DMFTwDFT-master/bin/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jatin/DMFTwDFT-master/bin/DMFT.py", line 4, in <module>
    import numpy as np
  File "/home/jatin/DMFTwDFT-master/bin/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/jatin/DMFTwDFT-master/bin/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/jatin/DMFTwDFT-master/bin/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/jatin/DMFTwDFT-master/bin/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/jatin/DMFTwDFT-master/bin/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray'.

I tried to reinstall `numpy`, but it still throwing the same error. 

I will be thankful for any suggestion regarding the solution.

Best Regatds
Jatin.

**Comment by uthpalaherath** [comment]
Dear Jatin,

I'm extremely sorry for not getting back to you sooner. We have moved the DMFTwDFT project to https://github.com/DMFTwDFT-project/DMFTwDFT which is Python 2 based for the time being. 

Instructions for installing libraries including skrams is given in the documentation:
https://dmftwdft-project.github.io/DMFTwDFT/installation.html

Please try again with these updates and see if it works. Otherwise let me know and I can help you to get it work. 

Thanks,

Best regards,
Uthpala

**Comment by uthpalaherath** [comment]
Hi @cmtcl18, 

We have released the latest version of DMFTwDFT (I know it's been 6 years lol). If you're still interested, give it another shot.
